# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1256, 875)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(90, 110, 501, 491))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_video_widget = QVideoWidget(self.groupBox)
        self.input_video_widget.setMinimumSize(QtCore.QSize(100, 100))
        self.input_video_widget.setObjectName("input_video_widget")
        self.verticalLayout.addWidget(self.input_video_widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.predict_progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.predict_progressBar.setProperty("value", 0)
        self.predict_progressBar.setObjectName("predict_progressBar")
        self.horizontalLayout_2.addWidget(self.predict_progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.import_media_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.import_media_pushButton.setObjectName("import_media_pushButton")
        self.horizontalLayout.addWidget(self.import_media_pushButton)
        self.start_predict_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.start_predict_pushButton.setObjectName("start_predict_pushButton")
        self.horizontalLayout.addWidget(self.start_predict_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(640, 110, 491, 491))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.output_video_widget = QVideoWidget(self.groupBox_2)
        self.output_video_widget.setMinimumSize(QtCore.QSize(100, 100))
        self.output_video_widget.setObjectName("output_video_widget")
        self.verticalLayout_2.addWidget(self.output_video_widget)
        self.open_predict_file_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.open_predict_file_pushButton.setObjectName("open_predict_file_pushButton")
        self.verticalLayout_2.addWidget(self.open_predict_file_pushButton)
        self.predict_info_plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.predict_info_plainTextEdit.setGeometry(QtCore.QRect(150, 700, 951, 81))
        self.predict_info_plainTextEdit.setObjectName("predict_info_plainTextEdit")
        self.author_label = QtWidgets.QLabel(self.centralwidget)
        self.author_label.setGeometry(QtCore.QRect(980, 60, 91, 31))
        self.author_label.setObjectName("author_label")
        self.gpu_info_label = QtWidgets.QLabel(self.centralwidget)
        self.gpu_info_label.setGeometry(QtCore.QRect(540, 800, 271, 31))
        self.gpu_info_label.setObjectName("gpu_info_label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(540, 660, 158, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.play_pushButton = QtWidgets.QPushButton(self.widget)
        self.play_pushButton.setObjectName("play_pushButton")
        self.horizontalLayout_3.addWidget(self.play_pushButton)
        self.pause_pushButton = QtWidgets.QPushButton(self.widget)
        self.pause_pushButton.setObjectName("pause_pushButton")
        self.horizontalLayout_3.addWidget(self.pause_pushButton)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(500, 610, 251, 41))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.video_horizontalSlider = QtWidgets.QSlider(self.widget1)
        self.video_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.video_horizontalSlider.setObjectName("video_horizontalSlider")
        self.horizontalLayout_4.addWidget(self.video_horizontalSlider)
        self.video_percent_label = QtWidgets.QLabel(self.widget1)
        self.video_percent_label.setObjectName("video_percent_label")
        self.horizontalLayout_4.addWidget(self.video_percent_label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1256, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "输入媒体"))
        self.label.setText(_translate("MainWindow", "推理进度："))
        self.import_media_pushButton.setText(_translate("MainWindow", "导入"))
        self.start_predict_pushButton.setText(_translate("MainWindow", "推理"))
        self.groupBox_2.setTitle(_translate("MainWindow", "输出媒体"))
        self.open_predict_file_pushButton.setText(_translate("MainWindow", "在文件中查看"))
        self.author_label.setText(_translate("MainWindow", "黄显钧 出品"))
        self.gpu_info_label.setText(_translate("MainWindow", "TextLabel"))
        self.play_pushButton.setText(_translate("MainWindow", "播放"))
        self.pause_pushButton.setText(_translate("MainWindow", "暂停"))
        self.video_percent_label.setText(_translate("MainWindow", "0 %"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
